on:
  workflow_dispatch:
  schedule:
    - cron:  '0 21 * * *'
name: Scrape Data
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      run: npm install
    - name: Scrape
      run: ./run.sh
      env:
        MOSRUKEY: ${{ secrets.MOSRUKEY }}
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'main'
